baseURL: https://ryankearney.com/
languageCode: en-us
title: Ryan Kearney
theme: after-dark
paginate: 11

enableRobotsTXT: true
disqusShortname: ryankearney
SectionPagesMenu: main
footnoteReturnLinkContents: ↩

permalinks:
  post: /:year/:month/:title/

params:
  description: "" # Suggested, controls default description meta
  author: "Ryan Kearney" # Optional, controls author name display on posts
  hide_author: false # Optional, set true to hide author name on posts
  show_menu: false # Optional, set true to enable section menu
  powered_by: false # Optional, set false to disable credits
  images:
    - "https://source.unsplash.com/category/technology/2000x1322"
  theme_variant: "" # Optional, for use to overriding default theme
